pre-commit:
  parallel: true
  commands:
    type-check:
      glob: "*.{ts,tsx}"
      run: npx tsc --noEmit

    eslint:
      glob: "*.{js,ts,tsx}"
      run: npx eslint {staged_files}

    prettier:
      glob: "*.{js,ts,tsx,json,css,md}"
      run: npx prettier --write {staged_files}
